### ISSUE TITLE
Request to Adding an MIT License

### ISSUE THREAD

**Issue by bckk-yzhou** [sauvikdolui/swiftlogger#4]
Hi, 
We are interested in this repository and want to use the source code in our own commercial product.
Would you please add an **MIT license** to this repository?
The license can be found as following link:
https://choosealicense.com/licenses/mit/

Thanks in advance.

**Comment by sauvikdolui** [comment]
Hi @bckk-yzhou ,

Thanks for considering this project in your project. That really good to know that this library is becoming helpful to the community. I have added the MIT License. 

I am also available for freelancing in my spare time, if there is any opportunity, please let me know.

Thanks,
Sauvik.

**Comment by bckk-yzhou** [comment]
Hi @sauvikdolui ,

Thank you for adding the MIT license to the library.
Regarding the freelancing, we'll take it into consider if there is an opportunity.
Let's keep in touch then.

Thanks,
Zhou
